### ISSUE TITLE
Why does the AWS Template have a NAT instance

### ISSUE THREAD

**Issue by eastlondoner** [dcos/dcos-docs#235] opened 2016-04-19 16:29 UTC
What is the purpose of the NAT server.
I am familiar with what NAT is.
But this just seems to be a random Ubuntu server thrown into the template.

**Comment by eastlondoner** [comment] 2016-04-19 17:07
I think I put this in the wrong place.
*gets coat*

**Comment by lingmann** [comment] 2016-04-21 17:53
Hi @eastlondoner, in an AWS VPC it is necessary for there to be a NAT instance (or their new NAT service) in order for nodes to have outgoing internet access.

**Comment by eastlondoner** [comment] 2016-04-21 20:21
you're thinking of a vpc endpoint, no?

**Comment by naphthalene** [comment] 2016-05-02 20:09
It makes sense why the template was designed this way: click once, wait a while, and you have a DC/OS system up in a fresh VPC, subnet, with a NAT and everything. However its nearly impossible to integrate the cloud formation template with an existing VPC. It would be pretty sweet to use cloud formation if only there was a template that operates under the assumption that there is already a VPC and subnet created for DC/OS deployment.

**Comment by lingmann** [comment] 2016-05-02 21:19
Hi @naphthalene we are working on "Advanced" versions of the AWS templates which give you the ability to use Cloudformation to install DC/OS to existing VPC's and security groups. Once we have documentation and links for these templates ready, the details will be available on https://dcos.io/docs

**Comment by mhausenblas** [comment] 2016-05-03 04:07
This seems more like a discussion than an actionable thing. I'll close it since we're migrating to [Jira](https://dcosjira.atlassian.net). If you guys feel you want to continue the discussion, you can do it over there, on Slack or on the mailing list ;)

**Closed by mhausenblas** 2016-05-03 04:07 UTC

**Comment by naphthalene** [comment] 2016-05-03 14:49
@lingmann thank you for your reply! That's great to hear.
